apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    app: nginx
    tier: frontend
spec:
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 6
  selector:
    matchLabels:
      app: myapp

