apiVersion: v1
kind: Pod
metadata:
  name:  webapp-pod
  labels:
    name: webapp-color
spec:
  containers:
    - name:  webapp-color
      image:  kodekloud/simple-webapp-mysql
      envFrom:
        - secretRef:
            name: db-secret



